openapi: 3.0.0
servers:
  - description: Local
    url: http://localhost:5000/
info:
  description: Server template for build-app. Project "full".
  version: '1.0.0'
  title: Full Template
tags:
  - name: 'User'
    description: 'Operations about user'
    externalDocs:
      description: 'Find out more about our store'
      url: 'http://swagger.io'
  - name: 'Category'
    description: 'Everything about your Categories'
    externalDocs:
      description: 'Find out more'
      url: 'http://swagger.io'
  - name: 'Record'
    description: 'Everything about Records'
security:
  - ApiKeyAuth: []
paths:
  /api/current-user:
    $ref: './user/resources/user.yaml'
  /api/login:
    $ref: './user/resources/login.yaml'
  /api/sign-up:
    $ref: './user/resources/signUp.yaml'
  /api/activate/{token}:
    $ref: './user/resources/activate.yaml'
  /api/password-forgot:
    $ref: './user/resources/passwordForgot.yaml'
  /api/password-reset/{token}:
    $ref: './user/resources/resetToken.yaml'
  /api/password-reset:
    $ref: './user/resources/passwordReset.yaml'
  /api/categories:
    $ref: './category/resources/list.yaml'
  /api/category:
    $ref: './category/resources/create.yaml'
  /api/category/{id}:
    $ref: './category/resources/remove.yaml'
  /api/records:
    $ref: './record/resources/list.yaml'
  /api/record:
    $ref: './record/resources/create.yaml'
  /api/record/{id}:
    $ref: './record/resources/remove.yaml'
components:
  securitySchemes:
    ApiKeyAuth:
      type: 'apiKey'
      in: 'header'
      name: 'Authorization'
  requestBodies:
    $ref: './requests.yaml'
  schemas:
    $ref: './schemas.yaml'
  responses:
    $ref: './responses.yaml'
